### ISSUE TITLE
Issue installing the logstash-input-salesforce

### ISSUE THREAD

**Issue by praneel** [logstash-plugins/logstash-input-salesforce#13]
When I run this command to install the Salesforce plugin to extract data from Salesforce

bin/logstash-plugin install logstash-input-salesforce

I have this error

Validating logstash-input-salesforce
IOError: No route to host
send at org/jruby/ext/socket/RubyUDPSocket.java:441

googling does help me with a proper answer/explanation. So help appreciated.

logstash version 6.2

**Comment by guyboertje** [comment]
Are you trying to install the `logstash-input-salesforce` plugin on a machine that has no connection to the internet perhaps?
